const countriesEn = [
  { code: "AW", name: "Aruba" },
  { code: "AF", name: "Afghanistan" },
  { code: "AO", name: "Angola" },
  { code: "AI", name: "Anguilla" },
  { code: "AX", name: "Åland Islands" },
  { code: "AL", name: "Albania" },
  { code: "AD", name: "Andorra" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AS", name: "American Samoa" },
  { code: "AQ", name: "Antarctica" },
  { code: "TF", name: "French Southern and Antarctic Lands" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BI", name: "Burundi" },
  { code: "BE", name: "Belgium" },
  { code: "BJ", name: "Benin" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BD", name: "Bangladesh" },
  { code: "BG", name: "Bulgaria" },
  { code: "BH", name: "Bahrain" },
  { code: "BS", name: "Bahamas" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BL", name: "Saint Barthélemy" },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha" },
  { code: "BY", name: "Belarus" },
  { code: "BZ", name: "Belize" },
  { code: "BM", name: "Bermuda" },
  { code: "BO", name: "Bolivia" },
  { code: "BQ", name: "Caribbean Netherlands" },
  { code: "BR", name: "Brazil" },
  { code: "BB", name: "Barbados" },
  { code: "BN", name: "Brunei" },
  { code: "BT", name: "Bhutan" },
  { code: "BV", name: "Bouvet Island" },
  { code: "BW", name: "Botswana" },
  { code: "CF", name: "Central African Republic" },
  { code: "CA", name: "Canada" },
  { code: "CC", name: "Cocos (Keeling) Islands" },
  { code: "CH", name: "Switzerland" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CI", name: "Ivory Coast" },
  { code: "CM", name: "Cameroon" },
  { code: "CD", name: "DR Congo" },
  { code: "CG", name: "Republic of the Congo" },
  { code: "CK", name: "Cook Islands" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CV", name: "Cape Verde" },
  { code: "CR", name: "Costa Rica" },
  { code: "CU", name: "Cuba" },
  { code: "CW", name: "Curaçao" },
  { code: "CX", name: "Christmas Island" },
  { code: "KY", name: "Cayman Islands" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czechia" },
  { code: "DE", name: "Germany" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DK", name: "Denmark" },
  { code: "DO", name: "Dominican Republic" },
  { code: "DZ", name: "Algeria" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "ER", name: "Eritrea" },
  { code: "EH", name: "Western Sahara" },
  { code: "ES", name: "Spain" },
  { code: "EE", name: "Estonia" },
  { code: "ET", name: "Ethiopia" },
  { code: "FI", name: "Finland" },
  { code: "FJ", name: "Fiji" },
  { code: "FK", name: "Falkland Islands" },
  { code: "FR", name: "France" },
  { code: "FO", name: "Faroe Islands" },
  { code: "FM", name: "Micronesia" },
  { code: "GA", name: "Gabon" },
  { code: "GB", name: "United Kingdom" },
  { code: "GE", name: "Georgia" },
  { code: "GG", name: "Guernsey" },
  { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" },
  { code: "GN", name: "Guinea" },
  { code: "GP", name: "Guadeloupe" },
  { code: "GM", name: "Gambia" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "GR", name: "Greece" },
  { code: "GD", name: "Grenada" },
  { code: "GL", name: "Greenland" },
  { code: "GT", name: "Guatemala" },
  { code: "GF", name: "French Guiana" },
  { code: "GU", name: "Guam" },
  { code: "GY", name: "Guyana" },
  { code: "HK", name: "Hong Kong" },
  { code: "HM", name: "Heard Island and McDonald Islands" },
  { code: "HN", name: "Honduras" },
  { code: "HR", name: "Croatia" },
  { code: "HT", name: "Haiti" },
  { code: "HU", name: "Hungary" },
  { code: "ID", name: "Indonesia" },
  { code: "IM", name: "Isle of Man" },
  { code: "IN", name: "India" },
  { code: "IO", name: "British Indian Ocean Territory" },
  { code: "IE", name: "Ireland" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IS", name: "Iceland" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JE", name: "Jersey" },
  { code: "JO", name: "Jordan" },
  { code: "JP", name: "Japan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "KH", name: "Cambodia" },
  { code: "KI", name: "Kiribati" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "KR", name: "South Korea" },
  { code: "XK", name: "Kosovo" },
  { code: "KW", name: "Kuwait" },
  { code: "LA", name: "Laos" },
  { code: "LB", name: "Lebanon" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LC", name: "Saint Lucia" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LK", name: "Sri Lanka" },
  { code: "LS", name: "Lesotho" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "LV", name: "Latvia" },
  { code: "MO", name: "Macau" },
  { code: "MF", name: "Saint Martin" },
  { code: "MA", name: "Morocco" },
  { code: "MC", name: "Monaco" },
  { code: "MD", name: "Moldova" },
  { code: "MG", name: "Madagascar" },
  { code: "MV", name: "Maldives" },
  { code: "MX", name: "Mexico" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MK", name: "North Macedonia" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MM", name: "Myanmar" },
  { code: "ME", name: "Montenegro" },
  { code: "MN", name: "Mongolia" },
  { code: "MP", name: "Northern Mariana Islands" },
  { code: "MZ", name: "Mozambique" },
  { code: "MR", name: "Mauritania" },
  { code: "MS", name: "Montserrat" },
  { code: "MQ", name: "Martinique" },
  { code: "MU", name: "Mauritius" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "YT", name: "Mayotte" },
  { code: "NA", name: "Namibia" },
  { code: "NC", name: "New Caledonia" },
  { code: "NE", name: "Niger" },
  { code: "NF", name: "Norfolk Island" },
  { code: "NG", name: "Nigeria" },
  { code: "NI", name: "Nicaragua" },
  { code: "NU", name: "Niue" },
  { code: "NL", name: "Netherlands" },
  { code: "NO", name: "Norway" },
  { code: "NP", name: "Nepal" },
  { code: "NR", name: "Nauru" },
  { code: "NZ", name: "New Zealand" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PA", name: "Panama" },
  { code: "PN", name: "Pitcairn Islands" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PW", name: "Palau" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PL", name: "Poland" },
  { code: "PR", name: "Puerto Rico" },
  { code: "KP", name: "North Korea" },
  { code: "PT", name: "Portugal" },
  { code: "PY", name: "Paraguay" },
  { code: "PS", name: "Palestine" },
  { code: "PF", name: "French Polynesia" },
  { code: "QA", name: "Qatar" },
  { code: "RE", name: "Réunion" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "RW", name: "Rwanda" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SD", name: "Sudan" },
  { code: "SN", name: "Senegal" },
  { code: "SG", name: "Singapore" },
  { code: "GS", name: "South Georgia" },
  { code: "SJ", name: "Svalbard and Jan Mayen" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SV", name: "El Salvador" },
  { code: "SM", name: "San Marino" },
  { code: "SO", name: "Somalia" },
  { code: "PM", name: "Saint Pierre and Miquelon" },
  { code: "RS", name: "Serbia" },
  { code: "SS", name: "South Sudan" },
  { code: "ST", name: "São Tomé and Príncipe" },
  { code: "SR", name: "Suriname" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SE", name: "Sweden" },
  { code: "SZ", name: "Eswatini" },
  { code: "SX", name: "Sint Maarten" },
  { code: "SC", name: "Seychelles" },
  { code: "SY", name: "Syria" },
  { code: "TC", name: "Turks and Caicos Islands" },
  { code: "TD", name: "Chad" },
  { code: "TG", name: "Togo" },
  { code: "TH", name: "Thailand" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TK", name: "Tokelau" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TV", name: "Tuvalu" },
  { code: "TW", name: "Taiwan" },
  { code: "TZ", name: "Tanzania" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "UM", name: "United States Minor Outlying Islands" },
  { code: "UY", name: "Uruguay" },
  { code: "US", name: "United States" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VA", name: "Vatican City" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "VE", name: "Venezuela" },
  { code: "VG", name: "British Virgin Islands" },
  { code: "VI", name: "United States Virgin Islands" },
  { code: "VN", name: "Vietnam" },
  { code: "VU", name: "Vanuatu" },
  { code: "WF", name: "Wallis and Futuna" },
  { code: "WS", name: "Samoa" },
  { code: "YE", name: "Yemen" },
  { code: "ZA", name: "South Africa" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
];

const countriesNl = [
  { code: "AW", name: "Aruba" },
  { code: "AF", name: "Afghanistan" },
  { code: "AO", name: "Angola" },
  { code: "AI", name: "Anguilla" },
  { code: "AX", name: "Aland-eilanden" },
  { code: "AL", name: "Albanië" },
  { code: "AD", name: "Andorra" },
  { code: "AE", name: "Verenigde Arabische Emiraten" },
  { code: "AR", name: "Argentinië" },
  { code: "AM", name: "Armenië" },
  { code: "AS", name: "Amerikaans Samoa" },
  { code: "AQ", name: "Antarctica" },
  { code: "TF", name: "Franse zuidelijke en Antarctische gebieden" },
  { code: "AG", name: "Antigua en Barbuda" },
  { code: "AU", name: "Australië" },
  { code: "AT", name: "Oostenrijk" },
  { code: "AZ", name: "Azerbeidzjan" },
  { code: "BI", name: "Burundi" },
  { code: "BE", name: "België" },
  { code: "BJ", name: "Benin" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BD", name: "Bangladesh" },
  { code: "BG", name: "Bulgarije" },
  { code: "BH", name: "Bahrein" },
  { code: "BS", name: "Bahamas" },
  { code: "BA", name: "Bosnië-Herzegovina" },
  { code: "BL", name: "Sint-Bartholomeus" },
  { code: "SH", name: "Sint-Helena, Hemelvaart en Tristan da Cunha" },
  { code: "BY", name: "Wit-Rusland" },
  { code: "BZ", name: "Belize" },
  { code: "BM", name: "Bermuda" },
  { code: "BO", name: "Bolivia" },
  { code: "BQ", name: "Caribisch Nederland" },
  { code: "BR", name: "Brazilië" },
  { code: "BB", name: "Barbados" },
  { code: "BN", name: "Brune" },
  { code: "BT", name: "Bhutan" },
  { code: "BV", name: "Bouvet-eiland" },
  { code: "BW", name: "Botswana" },
  { code: "CF", name: "Centraal Afrikaanse Republiek" },
  { code: "CA", name: "Canada" },
  { code: "CC", name: "Cocos (Keeling) Eilanden" },
  { code: "CH", name: "Zwitserland" },
  { code: "CL", name: "Chili" },
  { code: "CN", name: "China" },
  { code: "CI", name: "Ivoorkust" },
  { code: "CM", name: "Kameroen" },
  { code: "CD", name: "DR Congo" },
  { code: "CG", name: "Republiek Congo" },
  { code: "CK", name: "Cookeilanden" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoren" },
  { code: "CV", name: "Kaapverdië" },
  { code: "CR", name: "Costa Rica" },
  { code: "CU", name: "Cuba" },
  { code: "CW", name: "Curacao" },
  { code: "CX", name: "Kersteiland" },
  { code: "KY", name: "Kaaiman Eilanden" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Tsjechië" },
  { code: "DE", name: "Duitsland" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DK", name: "Denemarken" },
  { code: "DO", name: "Dominicaanse Republiek" },
  { code: "DZ", name: "Algerije" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypte" },
  { code: "ER", name: "Eritrea" },
  { code: "EH", name: "Westelijke Sahara" },
  { code: "ES", name: "Spanje" },
  { code: "EE", name: "Estland" },
  { code: "ET", name: "Ethiopië" },
  { code: "FI", name: "Finland" },
  { code: "FJ", name: "Fidji" },
  { code: "FK", name: "Falkland Eilanden" },
  { code: "FR", name: "Frankrijk" },
  { code: "FO", name: "Faeröer" },
  { code: "FM", name: "Micronesië" },
  { code: "GA", name: "Gabon" },
  { code: "GB", name: "Verenigd Koninkrijk" },
  { code: "GE", name: "Georgië" },
  { code: "GG", name: "Guernsey" },
  { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" },
  { code: "GN", name: "Guinea" },
  { code: "GP", name: "Guadeloupe" },
  { code: "GM", name: "Gambia" },
  { code: "GW", name: "Guinee-Bissau" },
  { code: "GQ", name: "Equatoriaal-Guinea" },
  { code: "GR", name: "Griekenland" },
  { code: "GD", name: "Grenada" },
  { code: "GL", name: "Groenland" },
  { code: "GT", name: "Guatemala" },
  { code: "GF", name: "Frans-Guyana" },
  { code: "GU", name: "Guam" },
  { code: "GY", name: "Guyana" },
  { code: "HK", name: "Hongkong" },
  { code: "HM", name: "Heard- en McDonaldeilanden" },
  { code: "HN", name: "Honduras" },
  { code: "HR", name: "Kroatië" },
  { code: "HT", name: "Haïti" },
  { code: "HU", name: "Hongarije" },
  { code: "ID", name: "Indonesië" },
  { code: "IM", name: "Eiland Man" },
  { code: "IN", name: "Indië" },
  { code: "IO", name: "Brits-Indisch oceaan gebied" },
  { code: "IE", name: "Ierland" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Irak" },
  { code: "IS", name: "IJsland" },
  { code: "IL", name: "Israël" },
  { code: "IT", name: "Italië" },
  { code: "JM", name: "Jamaica" },
  { code: "JE", name: "Jersey" },
  { code: "JO", name: "Jordanië" },
  { code: "JP", name: "Japan" },
  { code: "KZ", name: "Kazachstan" },
  { code: "KE", name: "Kenia" },
  { code: "KG", name: "Kirgizië" },
  { code: "KH", name: "Cambodja" },
  { code: "KI", name: "Kiribat" },
  { code: "KN", name: "Saint Kitts en Nevis" },
  { code: "KR", name: "Zuid-Korea" },
  { code: "XK", name: "Kosovo" },
  { code: "KW", name: "Koeweit" },
  { code: "LA", name: "Laos" },
  { code: "LB", name: "Libanon" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libië" },
  { code: "LC", name: "Sint Lucia" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LK", name: "Sri Lanka" },
  { code: "LS", name: "Lesotho" },
  { code: "LT", name: "Litouwen" },
  { code: "LU", name: "Luxemburg" },
  { code: "LV", name: "Letland" },
  { code: "MO", name: "Macau" },
  { code: "MF", name: "Sint-Maarten" },
  { code: "MA", name: "Marokko" },
  { code: "MC", name: "Monaco" },
  { code: "MD", name: "Moldavië" },
  { code: "MG", name: "Madagascar" },
  { code: "MV", name: "Maldiven" },
  { code: "MX", name: "Mexico" },
  { code: "MH", name: "Marshall eilanden" },
  { code: "MK", name: "Noord-Macedonië" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MM", name: "Myanmar" },
  { code: "ME", name: "Montenegro" },
  { code: "MN", name: "Mongolië" },
  { code: "MP", name: "Noordelijke Mariana eilanden" },
  { code: "MZ", name: "Mozambique" },
  { code: "MR", name: "Mauritanië" },
  { code: "MS", name: "Montserrat" },
  { code: "MQ", name: "Martinique" },
  { code: "MU", name: "Mauritius" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Maleisië" },
  { code: "YT", name: "Mayotte" },
  { code: "NA", name: "Namibië" },
  { code: "NC", name: "Nieuw-Caledonië" },
  { code: "NE", name: "Niger" },
  { code: "NF", name: "Norfolkeiland" },
  { code: "NG", name: "Nigeria" },
  { code: "NI", name: "Nicaragua" },
  { code: "NU", name: "Nieuw" },
  { code: "NL", name: "Nederland" },
  { code: "NO", name: "Noorwegen" },
  { code: "NP", name: "Nepal" },
  { code: "NR", name: "Nauru" },
  { code: "NZ", name: "Nieuw-Zeeland" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PA", name: "Panama" },
  { code: "PN", name: "Pitcairneilanden" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Filippijnen" },
  { code: "PW", name: "Palau" },
  { code: "PG", name: "Papoea-Nieuw-Guinea" },
  { code: "PL", name: "Polen" },
  { code: "PR", name: "Puerto Rico" },
  { code: "KP", name: "Noord Korea" },
  { code: "PT", name: "Portugal" },
  { code: "PY", name: "Paraguay" },
  { code: "PS", name: "Palestina" },
  { code: "PF", name: "Frans-Polynesië" },
  { code: "QA", name: "Katar" },
  { code: "RE", name: "Bijeenkomst" },
  { code: "RO", name: "Roemenië" },
  { code: "RU", name: "Rusland" },
  { code: "RW", name: "Rwanda" },
  { code: "SA", name: "Saoedi-Arabië" },
  { code: "SD", name: "Soedan" },
  { code: "SN", name: "Senegal" },
  { code: "SG", name: "Singapore" },
  { code: "GS", name: "Zuid-Georgië" },
  { code: "SJ", name: "Svalbard en Jan Mayen" },
  { code: "SB", name: "Solomon eilanden" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SV", name: "El Salvador" },
  { code: "SM", name: "San Marino" },
  { code: "SO", name: "Somalië" },
  { code: "PM", name: "Saint Pierre en Miquelon" },
  { code: "RS", name: "Servië" },
  { code: "SS", name: "Zuid Soedan" },
  { code: "ST", name: "Sao Tomé en Principe" },
  { code: "SR", name: "Suriname" },
  { code: "SK", name: "Slowakije" },
  { code: "SI", name: "Slovenië" },
  { code: "SE", name: "Zweden" },
  { code: "SZ", name: "Eswatini" },
  { code: "SX", name: "Sint Maarten" },
  { code: "SC", name: "Seychellen" },
  { code: "SY", name: "Syrië" },
  { code: "TC", name: "Turks- en Caicoseilanden" },
  { code: "TD", name: "Tsjaad" },
  { code: "TG", name: "Gaan" },
  { code: "TH", name: "Thailand" },
  { code: "TJ", name: "Tadzjikistan" },
  { code: "TK", name: "Tokelau" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad en Tobago" },
  { code: "TN", name: "Tunesië" },
  { code: "TR", name: "Kalkoen" },
  { code: "TV", name: "Tuvalu" },
  { code: "TW", name: "Taiwan" },
  { code: "TZ", name: "Tanzania" },
  { code: "UG", name: "Oeganda" },
  { code: "UA", name: "Oekraïne" },
  { code: "UM", name: "Kleine afgelegen eilanden van de Verenigde Staten" },
  { code: "UY", name: "Uruguay" },
  { code: "US", name: "Verenigde Staten" },
  { code: "UZ", name: "Oezbekistan" },
  { code: "VA", name: "Vaticaanstad" },
  { code: "VC", name: "Saint Vincent en de Grenadines" },
  { code: "VE", name: "Venezuela" },
  { code: "VG", name: "Britse Maagdeneilanden" },
  { code: "VI", name: "Amerikaanse Maagdeneilanden" },
  { code: "VN", name: "Vietnam" },
  { code: "VU", name: "Vanuatu" },
  { code: "WF", name: "Wallis en Futuna" },
  { code: "WS", name: "Samoa" },
  { code: "YE", name: "Jemen" },
  { code: "ZA", name: "Zuid-Afrika" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
];

export const countries = {
  nl: countriesNl,
  en: countriesEn,
};
